apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: mono-repo-dev
  labels:
    app: fastapi
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: mono-repo-dev
data:
  ENV: "dev"
  LOG_LEVEL: "INFO"
  PORT: "8000"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: mono-repo-dev
type: Opaque
data:
  # These will be populated by external secret management
  riskdb_url: 
  snowflake_url: 
  analytics_db_url: 
