apiVersion: v1
kind: Service
metadata:
  name: dash-service
  namespace: {{ .Values.namespace }}
  labels:
    app: dash
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8050
    protocol: TCP
    name: http
  selector:
    app: dash
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dash-config
  namespace: {{ .Values.namespace }}
data:
  ENV: "{{ .Values.environment }}"
  PORT: "8050"
  LOG_LEVEL: "INFO"
  DASH_DEBUG: "false"
