apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.namespace }}
  labels:
    app: web
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: {{ .Values.namespace }}
data:
  ENV: "{{ .Values.environment }}"
  REACT_APP_API_URL: "{{ .Values.web.api_base_url }}"
  REACT_APP_ENVIRONMENT: "{{ .Values.environment }}"
