apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfigjson }}
