# Airflow Helm Values for Production Environment

nameOverride: airflow-prod
fullnameOverride: airflow-prod

airflow:
  version: "2.7.0"
  executor: KubernetesExecutor
  
  # Airflow configuration
  config:
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow-prod"
    
env:
  - name: ENV
    value: "prod"

# Web server configuration
webserver:
  replicas: 2
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# Scheduler configuration
scheduler:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# Worker configuration (KubernetesExecutor)
workers:
  replicas: 0  # Using KubernetesExecutor
  
# DAGs storage
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/your-org/mono-repo.git
    branch: main
    subPath: dags
    wait: 60

# Database (use external PostgreSQL)
postgresql:
  enabled: false

externalDatabase:
  type: postgresql
  host: riskdb-prod.cluster-xyz.us-east-1.rds.amazonaws.com
  port: 5432
  database: airflow_prod
  user: airflow
  passwordSecret: airflow-db-secret
  passwordSecretKey: password

# Redis (for KubernetesExecutor, we don't need Redis)
redis:
  enabled: false

# Service account
serviceAccount:
  create: true
  name: airflow-prod

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
